# Generated by Django 4.0.4 on 2024-09-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plane",
            options={"verbose_name_plural": "planes"},
        ),
        migrations.AlterField(
            model_name="plane",
            name="services",
            field=models.ManyToManyField(related_name="planes", to="airport.service"),
        ),
    ]
