# Generated by Django 4.1 on 2024-09-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_alter_plane_options_alter_plane_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plane",
            name="services",
            field=models.ManyToManyField(
                blank=True, related_name="planes", to="airport.service"
            ),
        ),
    ]
