services:
  airport:
    build:
      context: .
    image: airport-api-service
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db


  db:
    image: postgres:16.4-alpine3.20
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"


volumes:
  my_db:
  my_media:
